#!/usr/bin/env python3
"""Build Lessons.json — bilingual noir docket with locked Warsaw canon."""
import argparse
import json
from pathlib import Path

def loc(pl, en):
    return {"pl": pl, "en": en}

def beat(asset, pl, en, voice="caption"):
    return {"asset": asset, "caption": loc(pl, en), "voice": voice}

def delta(t=0, s=0, k=0, r=0):
    return {"tajemnica": t, "sad": s, "klient": k, "rozliczalnosc": r}

def ratio(statute, consequence, reflex, pattern, story=None):
    out = {
        "statute": loc(*statute),
        "consequence": loc(*consequence),
        "reflex": loc(*reflex),
        "pattern": loc(*pattern),
    }
    if story:
        out["patternStory"] = loc(*story)
    return out

STORY_MATA = (
    "Mata v. Avianca, 22-cv-1461 (PKC), S.D.N.Y., 22 czerwca 2023. Pełnomocnicy złożyli pismo z nieistniejącymi orzeczeniami wygenerowanymi przez ChatGPT i później dostarczyli ich fałszywe „kopie”. Sąd nałożył łącznie i solidarnie 5 000 USD na dwóch prawników i kancelarię oraz nakazał wysłać orzeczenie klientowi i sędziom, którym przypisano fikcyjne wyroki. Podstawą były amerykańska Rule 11 i alternatywnie inherent authority; to ilustracja staranności, nie źródło polskiej odpowiedzialności.",
    "Mata v. Avianca, 22-cv-1461 (PKC), S.D.N.Y., 22 June 2023. Counsel filed non-existent authorities generated by ChatGPT and later supplied fake “copies”. The court imposed a joint and several $5,000 penalty on two lawyers and their firm and ordered notice to the client and judges falsely named as authors. The grounds were US Rule 11 and, alternatively, inherent authority; this illustrates verification duties but is not a source of Polish liability.",
)

STORY_PARK = (
    "Park v. Kim, No. 22-2057, 2d Cir., 30 stycznia 2024. Pełnomocniczka Jae S. Lee zacytowała w reply brief nieistniejący wyrok stanowy wygenerowany przez ChatGPT i nie przeczytała go ani nie potwierdziła. Sąd skierował sprawę prawniczki do Grievance Panel i nakazał przekazać orzeczenie klientce Minhye Park. To przykład amerykański, niewiążący w Polsce.",
    "Park v. Kim, No. 22-2057, 2d Cir., 30 January 2024. Counsel Jae S. Lee cited a non-existent state decision generated by ChatGPT in a reply brief and had neither read nor confirmed it. The court referred counsel to its Grievance Panel and ordered the decision supplied to client Minhye Park. This is a US illustration and is not binding in Poland.",
)

STORY_CORK = (
    "Cork & Anor v Smith [2026] EWHC 1199 (Ch), ICC Judge Mullen, 22 maja 2026. Pinsent Masons — nie darmowy chat z ulicy — w sprawie o block transfer w upadłości wstawili do listów do sądu „cytat” z Insolvency Rules, którego nie ma w statute. Sędzia sprawdził legislation.gov.uk. Junior jeszcze raz użył firmowego AI do wyjaśnienia. Sąd: dwukrotne wprowadzenie w błąd, „cavalier attitude”, publiczna nagana; kancelaria sama zgłosiła się do SRA.",
    "Cork & Anor v Smith [2026] EWHC 1199 (Ch), ICC Judge Mullen, 22 May 2026. Pinsent Masons — not a street ChatGPT — put into letters to the court a “quote” from the Insolvency Rules that is not in the statute. The judge checked legislation.gov.uk. A junior then used the firm’s own AI again to “explain”. The court: the court was misled twice, a “cavalier attitude”, a public admonishment; the firm self-referred to the SRA.",
)

STORY_UODO = (
    "Decyzja Prezesa UODO DKN.5131.31.2022 z 20 kwietnia 2023. Rzecznik Dyscyplinarny Izby Adwokackiej w X — nazwa izby została zanonimizowana — wysłał nagranie rozprawy rozwodowej na niezaszyfrowanym pendrive. Przesyłka dotarła uszkodzona, bez nośnika. Kara wyniosła 23 580 zł. Nieprawomocnym według CBOSA wyrokiem z 17 kwietnia 2024 r., II SA/Wa 1342/23, WSA w Warszawie oddalił skargę i zaakceptował kwalifikację rzecznika jako administratora.",
    "Polish DPA decision DKN.5131.31.2022 of 20 April 2023. The Disciplinary Counsel of Bar Association X—the association’s name was anonymised—sent a divorce-hearing recording on an unencrypted USB drive. The parcel arrived damaged and the device was missing. The fine was PLN 23,580. In a judgment recorded by CBOSA as non-final, II SA/Wa 1342/23 of 17 April 2024, the Warsaw administrative court dismissed the challenge and accepted that the disciplinary counsel was the controller.",
)

STORY_THOMAS = (
    "Thomas v. Corbyn Restaurant Development Corp., D083655, California Court of Appeal, 27 maja 2025. Oszust podszył się najpierw pod administratorkę kancelarii powoda, a potem pod rzekomego pracownika finansowego, i zmienił uzgodniony czek na przelew. Sąd utrzymał ponowną zapłatę 475 000 USD i przyjął ocenę strony najlepiej mogącej zapobiec oszustwu, z możliwością podziału straty według zwykłej staranności. To niewiążąca w Polsce analogia BEC.",
    "Thomas v. Corbyn Restaurant Development Corp., D083655, California Court of Appeal, 27 May 2025. The imposter first posed as the plaintiff firm’s administrator and then as a purported finance employee, changing the agreed cheque into a wire. The court affirmed enforcement of the $475,000 settlement and used a best-positioned-to-prevent test that permits apportionment based on ordinary care. This is a non-binding BEC analogy in Poland.",
)

STORY_HEPPNER = (
    "United States v. Heppner, No. 25 Cr. 503 (JSR), S.D.N.Y., 17 lutego 2026. Oskarżony sam używał konsumenckiej wersji Claude’a i później przekazał dokumenty obrońcom. Sąd odmówił ochrony attorney-client privilege oraz work-product: komunikacja nie była z prawnikiem ani poufna, a praca nie powstała na polecenie obrońcy. To amerykańskie orzeczenie dowodowe, nie wykładnia polskiej tajemnicy zawodowej.",
    "United States v. Heppner, No. 25 Cr. 503 (JSR), S.D.N.Y., 17 February 2026. The defendant independently used consumer Claude and later supplied the documents to counsel. The court rejected attorney-client privilege and work-product protection: the communication was neither with a lawyer nor confidential, and the work was not directed by counsel. This is a US evidentiary ruling, not an interpretation of Polish professional secrecy.",
)

def choice(cid, kind, verdict, d, title, subtitle, rat):
    return {
        "id": cid,
        "kind": kind,
        "verdict": verdict,
        "delta": d,
        "title": loc(*title),
        "subtitle": loc(*subtitle),
        "ratio": rat,
    }

def awareness(threat, minimize, practice, watch):
    return {
        "threat": loc(*threat),
        "minimize": loc(*minimize),
        "practice": loc(*practice),
        "watchFor": [loc(*w) for w in watch],
    }

lessons = [
    {
        "id": "01-sygnatura",
        "order": 1,
        "demo": True,
        "exhibit": "pleading",
        "hero": "Mission01",
        "tone": "shadow",
        "title": loc("Sygnatura z niebytu", "Docket from nowhere"),
        "subtitle": loc("Apelacja · prawa autorskie", "Appeal · copyright"),
        "deadline": loc("Termin wniesienia: dziś, 23:59", "Filing deadline: today, 23:59"),
        "context": loc(
            "Piąte piętro, biurowiec od Świętokrzyskiej. Klient — software house z „znajomymi w resorcie” — chce apelacji o kod źródłowy jeszcze dziś. Aplikant Filip Iglica kładzie pismo. Partner Chropot dzwoni z pociągu PKP Warszawa–Kraków: „Stempel do północy albo tracimy wokandę.”",
            "Fifth floor, office block off Świętokrzyska. The client — a software house with “friends in the ministry” — wants a source-code appeal tonight. Trainee Filip Iglica drops the pleading. Partner Chropot calls from the Warsaw–Kraków train: “Stamp it by midnight or we miss the docket.”",
        ),
        "beats": [
            beat("OfficeNight",
                 "Apelacja o kod źródłowy. Termin: dziś, 23:59. Na piątym piętrze świeci już tylko jedna lampa.",
                 "A source-code appeal. Deadline: today, 23:59. Only one lamp is still lit on the fifth floor."),
            beat("AplikantIglica",
                 "Uzasadnienie gotowe. Copilot uzupełnił orzecznictwo — trzy sygnatury i trzy mocne tezy.",
                 "The reasons are ready. Copilot completed the case law — three docket numbers and three strong holdings.",
                 "balloon"),
            beat("PartnerChropot",
                 "Jestem w pociągu. Stempel do północy — albo tracimy termin.",
                 "I am on the train. Stamp it by midnight — or we miss the deadline.",
                 "balloon"),
            beat("Mission01",
                "Na wydruku: trzy sygnatury SN i cytaty brzmiące jak gotowe tezy. Pieczęć czeka obok.",
                "On the printout: three Supreme Court docket numbers and quotes that read like finished holdings. The stamp waits beside them."),
        ],
        "exhibitLabel": loc("APELACJA — fragment uzasadnienia", "APPEAL — excerpt from the reasons"),
        "exhibitText": loc(
            "1. SN III CZP 12/22 — „ograniczenie w chmurze nie znosi autorskich praw majątkowych do kodu.”\n2. SN I CSK 441/19 — licencja MIT „milcząco obejmuje SaaS”.\n3. SN III CSK 88/21 — „repozytorium publiczne to publikacja w rozumieniu pr. aut.”",
            "1. SC III CZP 12/22 — “a cloud limitation does not extinguish economic copyright in code.”\n2. SC I CSK 441/19 — an MIT licence “silently covers SaaS”.\n3. SC III CSK 88/21 — “a public repository is publication under copyright law.”",
        ),
        "innerVoice": loc(
            "Numery i cytaty wyglądają formalnie. Co trzeba zobaczyć w pełnym tekście orzeczenia, zanim pod pismem znajdzie się twój podpis?",
            "The numbers and quotations look formal. What must you see in the full judgment before your signature goes under the pleading?",
        ),
        "redFlags": [
            loc("Fraza „ograniczenie w chmurze” brzmi jak model językowy, nie jak SN.", "The phrase “limitation in the cloud” sounds like a language model, not the Supreme Court."),
            loc("Prawdziwa sygnatura została połączona ze zmyśloną tezą — samo znalezienie numeru nie wystarcza.", "A real docket was paired with an invented holding — finding the number alone is not enough."),
            loc("Partner jest w pociągu — presja czasu nie zastępuje weryfikacji.", "The partner is on a train — time pressure is not verification."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(s=-45, r=-25),
                ("STEMPEL", "STAMP"),
                ("Podpisz i wyślij", "Sign and file"),
                ratio(
                    ("Art. 3 k.p.c. wymaga od stron i uczestników czynności zgodnych z dobrymi obyczajami oraz wyjaśnień zgodnych z prawdą. Pełnomocnik odpowiada za rzetelność pisma; kwalifikacja z art. 4¹ k.p.c. zależy od okoliczności.",
                     "Polish CCP art. 3 requires parties and participants to act consistently with good procedural customs and give truthful explanations. Counsel remains responsible for the filing; whether CCP art. 4¹ applies depends on the circumstances."),
                    ("Możliwe są wezwanie do wyjaśnień, skutki kosztowe i odpowiedzialność dyscyplinarna; nie są one automatyczne. Mata i Park ilustrują sankcje amerykańskie, nie polską podstawę prawną.",
                     "Possible consequences include an order to explain, costs and disciplinary exposure; none is automatic. Mata and Park illustrate US sanctions, not a Polish legal basis."),
                    ("Otwórz pełny tekst orzeczenia i sprawdź tezę w kontekście. Portal SN lub komercyjna baza pomagają szukać; urzędowym źródłem aktu normatywnego jest właściwy dziennik urzędowy, nie ISAP.",
                     "Open the full decision and check the holding in context. The Supreme Court portal or a commercial database helps with research; Polish legislation is officially promulgated in the relevant official journal, not in ISAP."),
                    ("Mata v. Avianca, S.D.N.Y. 22 Jun 2023, $5,000. Park v. Kim, 2d Cir. 2024. Cork v Smith / Pinsent Masons, May 2026.",
                     "Mata v. Avianca, S.D.N.Y. 22 Jun 2023, $5,000. Park v. Kim, 2d Cir. 2024. Cork v Smith / Pinsent Masons, May 2026."),
                    STORY_MATA,
                ),
            ),
            choice(
                "reject", "reject", "incomplete", delta(k=-10, r=+2),
                ("ODRZUT", "REJECT"),
                ("Odrzuć pismo", "Reject the pleading"),
                ratio(
                    ("§ 23e KEA (tekst jednolity ogłoszony 23 czerwca 2026) — technologia ma charakter wspomagający; adwokat zachowuje własną ocenę i odpowiedzialność. Tajemnica z art. 6 Pr. o adwokaturze nie jest tu osią — osią jest rzetelność pisma.",
                     "KEA § 23e (consolidated text published 23 June 2026) makes technology auxiliary while the advocate retains judgment and responsibility. Secrecy under art. 6 of the Bar Act is not the central issue here; filing accuracy is."),
                    ("Klient czeka. Odrzut bez uzasadnienia psuje relację, ale chroni wokandę. Iglica musi przepisać uzasadnienie na prawdziwych orzeczeniach.",
                     "The client is waiting. A bare rejection bruises the relationship but saves the docket. Iglica must rewrite on real authorities."),
                    ("Odrzut + jedna linia: które sygnatury nie istnieją. Nie zostawiaj aplikanta z „popraw”.",
                     "Reject plus one line: which citations do not exist. Do not leave the trainee with “fix it”."),
                    ("Pinsent Masons / Cork 2026: halucynacja w kancelarii, nie w ChatGPT z ulicy.",
                     "Pinsent Masons / Cork 2026: the hallucination sat inside the firm, not in a street ChatGPT."),
                    STORY_CORK,
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(s=+8, r=+10),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("LEX / ISAP", "LEX / ISAP"),
                ratio(
                    ("Akty normatywne ogłasza się w dziennikach urzędowych. ISAP jest pomocniczą bazą informacyjną. Orzeczenie weryfikujesz w oficjalnym portalu sądu lub wiarygodnej bazie, czytając pełny tekst.",
                     "Legislation is promulgated in official journals. ISAP is an informational aid. Verify a judgment in the court’s official portal or a reliable database and read the full text."),
                    ("Dwie sygnatury są prawdziwe, ale przypisane im tezy są zmyślone; trzecia ma błędny symbol. Iglica przyznaje, że Copilot „uzupełnił” uzasadnienie.",
                     "Two docket numbers are real but the attributed holdings are invented; the third uses the wrong case code. Iglica admits Copilot “completed” the reasons."),
                    ("Każdy cytat: otwórz pełny tekst, potwierdź sąd, datę, tezę i kontekst. Jeśli tego nie zrobiłeś — nie podpisuj.",
                     "For every citation, open the full text and confirm the court, date, holding and context. If you have not done that, do not sign."),
                    ("Park v. Kim, 2d Cir. 2024 — ten sam obowiązek: otwórz sentencję.",
                     "Park v. Kim, 2d Cir. 2024 — the same duty: open the holding."),
                    STORY_PARK,
                ),
            ),
        ],
    },
    {
        "id": "02-szept",
        "hero": "Mission02",
        "tone": "shadow",
        "order": 2,
        "demo": False,
        "exhibit": "prompt",
        "title": loc("Szept w chmurze", "Whisper in the cloud"),
        "subtitle": loc("SPA · ChatGPT", "SPA · ChatGPT"),
        "deadline": loc("Due diligence: jutro rano", "Due diligence: tomorrow morning"),
        "context": loc(
            "To samo biurko, to samo 5. piętro. Holding z zapleczem politycznym sprzedaje spółkę. Iglica wkleił do publicznego ChatGPT fragment SPA — ceny, earn-out, nazwiska członków zarządu. „Skróci recenzję. Przecież to nie jest tajemnica państwowa.”",
            "Same desk, same 5th floor. A holding with political cover is selling a company. Iglica pasted an SPA excerpt into public ChatGPT — prices, earn-out, directors’ names. “It will shorten the review. It is not a state secret.”",
        ),
        "beats": [
            beat("OfficeNight",
                 "Due diligence zaczyna się jutro rano. SPA zawiera cenę, earn-out i nazwiska członków zarządu.",
                 "Due diligence starts tomorrow morning. The SPA contains the price, earn-out and directors’ names."),
            beat("AplikantIglica",
                 "Wkleiłem fragment SPA do chatgpt.com. Tylko po to, żeby szybciej dostać listę ryzyk.",
                 "I pasted part of the SPA into chatgpt.com. Only to get the risk list faster.",
                 "balloon"),
            beat("Mission02",
                 "Na ekranie: darmowe konto konsumenckie. W historii rozmowy nadal widać kwoty i key persons.",
                 "On screen: a free consumer account. The chat history still shows the figures and key persons."),
            beat("MecenasPOV",
                 "Teczka SPA leży obok laptopa. Iglica pyta, czy wystarczy teraz usunąć rozmowę.",
                 "The SPA file lies beside the laptop. Iglica asks whether deleting the chat now will be enough."),
        ],
        "exhibitLabel": loc("PROMPT — zrzut z przeglądarki", "PROMPT — browser dump"),
        "exhibitText": loc(
            "You are a Polish M&A lawyer. Summarise risks in this SPA:\n[TARGET S.A., NIP …, earn-out 12 mln zł, covenant not to compete, lista key persons: …]\nKonto: darmowe, chatgpt.com, brak DPA.",
            "You are a Polish M&A lawyer. Summarise risks in this SPA:\n[TARGET S.A., tax ID …, earn-out PLN 12m, non-compete, key persons: …]\nAccount: free, chatgpt.com, no DPA.",
        ),
        "innerVoice": loc(
            "Treść została już wysłana do zewnętrznej usługi. Jakie fakty o koncie, danych i warunkach dostawcy musisz ustalić przed kolejnym ruchem?",
            "The content has already been sent to an external service. What facts about the account, data and provider terms must you establish before the next move?",
        ),
        "redFlags": [
            loc("Konto konsumenckie: dostawca działa na własnych warunkach, a nie jako procesor kancelarii na podstawie uzgodnionej umowy powierzenia.", "Consumer account: the provider acts under its consumer terms, not as the firm’s processor under an agreed data-processing contract."),
            loc("SPA zawiera dane osobowe i informacje objęte tajemnicą zawodową; część warunków może też spełniać przesłanki tajemnicy przedsiębiorstwa.", "The SPA contains personal data and information covered by professional secrecy; some terms may also meet the statutory trade-secret conditions."),
            loc("§ 23e: zakaz wprowadzania tajemnic do narzędzi niezapewniających ochrony.", "§ 23e: no secrets in tools that do not guarantee protection."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(t=-50, r=-30),
                ("STEMPEL", "STAMP"),
                ("Zostaw prompt, bierz notatkę", "Keep the prompt, take the memo"),
                ratio(
                    ("Art. 6 Prawa o adwokaturze oraz art. 3 ust. 3 ustawy o radcach prawnych obejmują tajemnicą wszystko, czego prawnik dowiedział się w związku z udzielaniem pomocy prawnej. § 23e KEA zabrania adwokatowi dopuszczać do przetwarzania takich informacji przez narzędzia niezapewniające należytej ochrony.",
                     "Art. 6 of the Bar Act and art. 3(3) of the Legal Advisers Act cover everything learned in connection with legal assistance. KEA § 23e bars an advocate from allowing such information to be processed by tools that do not provide proper protection."),
                    ("Możliwe są utrata zaufania klienta i odpowiedzialność dyscyplinarna. Dla danych osobowych trzeba udokumentować ocenę naruszenia; obowiązek zgłoszenia z art. 33 i zawiadomienia z art. 34 RODO zależy od ryzyka, nie od samego użycia narzędzia.",
                     "Possible consequences include loss of client trust and disciplinary exposure. For personal data, the breach assessment must be documented; notification under GDPR arts. 33 and 34 depends on risk, not merely on use of the tool."),
                    ("Zanim wkleisz: ustal, czy treść jest objęta tajemnicą lub zawiera dane osobowe. Sam DPA ani wyłączenie treningu nie wystarcza — potrzebna jest ocena warunków, celu, dostępu, retencji, transferów i zabezpieczeń zgodna z polityką kancelarii.",
                     "Before pasting, determine whether the content is privileged or contains personal data. A DPA or training opt-out alone is insufficient — assess terms, purpose, access, retention, transfers and safeguards under firm policy."),
                    ("United States v. Heppner, S.D.N.Y. 2026 — publiczny model nie jest pokojem narad.",
                     "United States v. Heppner, S.D.N.Y. 2026 — a public model is not a conference room."),
                    STORY_HEPPNER,
                ),
            ),
            choice(
                "reject", "reject", "incomplete", delta(t=+5, k=-5),
                ("ODRZUT", "REJECT"),
                ("Każ skasować sesję, przepisać lokalnie", "Kill the session, rewrite locally"),
                ratio(
                    ("Art. 6 Pr. o adwokaturze / art. 3 ust. 3 u.r.pr. — obowiązek zachowania tajemnicy jest bezterminowy i nie zależy od tego, czy „wszyscy i tak to wiedzą”.",
                     "Art. 6 Bar Act / art. 3(3) Legal Advisers Act — secrecy is indefinite and does not care that “everyone already knows”."),
                    ("Usunięcie historii nie cofa ujawnienia. Zabezpieczasz informacje o incydencie, zgłaszasz go zgodnie z procedurą i oceniasz osobno tajemnicę zawodową, umowę z klientem oraz ryzyko dla danych osobowych.",
                     "Deleting chat history does not undo disclosure. Preserve incident facts, report under firm procedure, and assess professional secrecy, the client agreement and personal-data risk separately."),
                    ("Domyślnie nie wklejaj akt do narzędzia konsumenckiego. Dopuszczone narzędzie musi przejść ocenę prawną, bezpieczeństwa i konfiguracji; anonimizacja musi być rzeczywista, nie tylko polegać na usunięciu nazwisk.",
                     "By default, do not paste files into a consumer tool. An approved tool requires legal, security and configuration review; anonymisation must be effective, not merely removal of names."),
                    ("United States v. Heppner, S.D.N.Y. 2026 — wklejenie do Claude’a nie tworzy tajemnicy.",
                     "United States v. Heppner, S.D.N.Y. 2026 — pasting into Claude does not create privilege."),
                    STORY_HEPPNER,
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(t=+8, r=+8),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("DPA / ustawienia / on-prem", "DPA / settings / on-prem"),
                ratio(
                    ("Art. 28 RODO ma zastosowanie, gdy dostawca przetwarza dane w imieniu kancelarii. W usłudze konsumenckiej dostawca może występować jako odrębny administrator. Art. 32 wymaga środków odpowiednich do ryzyka; § 23e KEA dotyczy ochrony tajemnicy i osobistej odpowiedzialności adwokata.",
                     "GDPR art. 28 applies where the provider processes data on the firm’s behalf. In a consumer service the provider may act as a separate controller. Article 32 requires measures appropriate to risk; KEA § 23e addresses secrecy and the advocate’s personal responsibility."),
                    ("Sprawdzasz rolę dostawcy, warunki usługi, retencję, dostęp ludzi, wykorzystanie do ulepszania modeli, transfery i możliwość skutecznego usunięcia. Ustawienie „nie trenuj” nie rozstrzyga pozostałych ryzyk.",
                     "Check the provider’s role, terms, retention, human access, model-improvement use, transfers and effective deletion. A “do not train” setting does not resolve the remaining risks."),
                    ("Drugi kanał przy AI: zatwierdzony rejestr narzędzi, analiza umowy i bezpieczeństwa oraz lista danych niedopuszczonych. Dla każdej sprawy stosuj minimalizację i kontrolę dostępu.",
                     "Second channel for AI: an approved tool register, contract and security review, and a prohibited-data list. Apply minimisation and access control to every matter."),
                    ("Heppner 2026: polityka prywatności dostawcy znosi oczekiwanie poufności.",
                     "Heppner 2026: the vendor’s privacy policy kills the expectation of confidentiality."),
                    STORY_HEPPNER,
                ),
            ),
        ],
    },
    {
        "id": "03-glos",
        "order": 3,
        "demo": True,
        "exhibit": "phone",
        "hero": "Mission03",
        "tone": "shadow",
        "title": loc("Głos z lotniska", "Voice from the airport"),
        "subtitle": loc("Środki powierzone · vishing", "Client money · vishing"),
        "deadline": loc("„Transakcja spada z afisza za 12 minut”", "“The deal drops off the board in 12 minutes”"),
        "context": loc(
            "Lampka na 5. piętrze. Na teczce: grupa budowlana, cichy inwestor, escrow 1,8 mln zł. W słuchawce — głos partnera Chropota, jak z pociągu, tylko że mówi o Lotnisku Chopina. Numer wychodzący: +48, ale domena w mailu potwierdzającym to mer1dian-trust.com. Na teczce klienta inny numer.",
            "The lamp on the fifth floor. On the file: a construction group, a quiet investor, PLN 1.8m in escrow. In the receiver — Partner Chropot’s voice, as if from the train, except he is talking about Chopin Airport. Caller ID is +48, but the confirming e-mail domain is mer1dian-trust.com. The client file has a different number.",
        ),
        "beats": [
            beat("OfficeNight",
                 "Na rachunku escrow czeka 1,8 mln zł środków powierzonych. Do zamknięcia transakcji zostało dwanaście minut.",
                 "PLN 1.8m of client money waits in escrow. Twelve minutes remain before the transaction closes."),
            beat("Mission03",
                 "Głos w słuchawce: „Mecenas, to Chropot. Nowy IBAN. Nie oddzwaniaj — wsiadam do samolotu.”",
                 "The voice in the receiver: “Counsel, it’s Chropot. New IBAN. Do not call back — I am boarding.”",
                 "balloon"),
            beat("PartnerChropot",
                 "W aktach: wcześniej zapisany numer Chropota i rachunek Meridian Trust. W mailu: mer1dian-trust.com.",
                 "In the file: Chropot’s previously recorded number and the Meridian Trust account. In the e-mail: mer1dian-trust.com."),
            beat("MecenasPOV",
                 "Dyspozycja zmienia rachunek dla całych 1,8 mln zł. Głos naciska, żeby nie używać numeru z teczki.",
                 "The instruction changes the account for the full PLN 1.8m. The voice insists that the number in the file must not be used."),
        ],
        "exhibitLabel": loc("NOTATKA ZE SŁUCHAWKI", "NOTE FROM THE HANDSET"),
        "exhibitText": loc(
            "„Mecenas, to Chropot. Zmiana rachunku escrow. Meridian Trust, IBAN DE… Proszę przelać 1,8 mln zł ze środków powierzonych. Mail z fakturą już jest. Nie dzwoń na komórkę — jestem na pokładzie.”",
            "“Counsel, it’s Chropot. Escrow account change. Meridian Trust, IBAN DE… Please wire PLN 1.8m from client money. The invoice e-mail is in. Don’t call the mobile — I’m boarding.”",
        ),
        "innerVoice": loc(
            "Masz głos, wiadomość i dane zapisane wcześniej w aktach. Który element naprawdę potwierdza tożsamość i dyspozycję?",
            "You have a voice, a message and details previously recorded in the file. Which element actually confirms identity and the instruction?",
        ),
        "redFlags": [
            loc("Domena mer1dian (jedynka) — BEC, nie Meridian.", "Domain mer1dian (the digit) — BEC, not Meridian."),
            loc("Zakaz kontaktu na znany numer = klasyka vishingu / deepfake’u głosu.", "A ban on calling the known number is textbook vishing / voice clone."),
            loc("Środki powierzone nie wychodzą na IBAN z telefonu.", "Client money does not leave on an IBAN from a phone call."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(k=-55, r=-40, t=-10),
                ("STEMPEL", "STAMP"),
                ("Zleć przelew", "Authorise the wire"),
                ratio(
                    ("Zakres umocowania, umowa i reguły środków klienta — dla adwokata w szczególności § 6 Regulaminu wykonywania zawodu, dla radcy art. 37 KERP — wyznaczają sposób dysponowania pieniędzmi. Callback i podwójna autoryzacja są środkami procedury, nie dosłownym brzmieniem tych norm.",
                     "Authority, the client agreement and client-money rules—in particular § 6 of the advocate-practice regulations and KERP art. 37 for legal advisers—govern the funds. Callback and dual approval are procedural controls, not the literal wording of those rules."),
                    ("1,8 mln zł może trafić do oszusta. Powstają ryzyka odszkodowawcze, ubezpieczeniowe, dyscyplinarne i — zależnie od faktów oraz winy — karne; żadna z tych kwalifikacji nie jest automatyczna.",
                     "PLN 1.8m may reach the fraudster. Civil, insurance, disciplinary and—depending on the facts and fault—criminal exposure may follow; none is automatic."),
                    ("Callback na numer z teczki, nie z maila i nie z rozmowy. Dwa osoby przy środkach. Żadnych IBAN-ów z telefonu.",
                     "Callback to the number on the file, not from the e-mail or the call. Two people on client money. No IBANs from a phone."),
                    ("Thomas v. Corbyn, Cal. Ct. App. 2025 — BEC na ugodę 475 000 USD. Ryzyko po stronie, która nie sprawdziła kanału.",
                     "Thomas v. Corbyn, Cal. Ct. App. 2025 — BEC against a USD 475,000 settlement. Loss sits with the side that did not check the channel."),
                    STORY_THOMAS,
                ),
            ),
            choice(
                "reject", "reject", "incomplete", delta(k=-15, r=-5),
                ("ODRZUT", "REJECT"),
                ("Rozłącz się i czekaj", "Hang up and wait"),
                ratio(
                    ("Odrzut bez weryfikacji zostawia dyspozycję w powietrzu. Jeśli to był prawdziwy Chropot — klient traci transzę. Jeśli fałszywy — nadal nie masz protokołu.",
                     "A rejection without verification leaves the instruction in the air. If it was the real Chropot — the client misses the tranche. If fake — you still have no protocol."),
                    ("Milczenie nie jest drugim kanałem. Za 12 minut ktoś inny w kancelarii może „pomóc”.",
                     "Silence is not a second channel. In 12 minutes someone else in the firm may “help”."),
                    ("Rozłącz, oddzwoń na numer z teczki, potwierdź IBAN z umowy escrow, nie z maila.",
                     "Hang up, call the file number, confirm the IBAN from the escrow contract, not from e-mail."),
                    ("Vishing + BEC: para, nie alternatywa. Głos i domena kłamią razem.",
                     "Vishing + BEC: a pair, not alternatives. Voice and domain lie together."),
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(k=+10, r=+12),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("Numer z teczki", "Number on the file"),
                ratio(
                    ("Procedura środków powierzonych wymaga identyfikacji osoby uprawnionej i potwierdzenia zmiany rachunku kanałem zapisanym wcześniej w aktach. RODO może mieć znaczenie dla bezpieczeństwa danych, ale nie jest podstawą autoryzacji przelewu.",
                     "Client-money procedure requires identification of the authorised person and confirmation of an account change through a channel recorded in advance. GDPR may govern data security, but it is not the legal basis for authorising the transfer."),
                    ("Chropot z teczki odbiera w pociągu i mówi: „nie dzwoniłem z lotniska”. Mail mer1dian idzie do CERT / banku. Przelew stoi.",
                     "The Chropot on the file picks up on the train: “I did not call from the airport.” The mer1dian e-mail goes to CERT / the bank. The wire stays."),
                    ("Tabliczka na biurku: numer callback | zakaz IBAN z telefonu | cztery oczy.",
                     "A plate on the desk: callback number | no IBAN from a phone | four eyes."),
                    ("Thomas v. Corbyn 2025 — myślnik i cyfra w domenie to ten sam mechanizm.",
                     "Thomas v. Corbyn 2025 — a hyphen or a digit in the domain is the same mechanism."),
                    STORY_THOMAS,
                ),
            ),
        ],
    },
    {
        "id": "04-prostokaty",
        "order": 4,
        "demo": True,
        "exhibit": "pdf",
        "hero": "Mission04",
        "tone": "shadow",
        "title": loc("Czerwone prostokąty", "Red rectangles"),
        "subtitle": loc("Ugoda patentowa · redakcja PDF", "Patent settlement · PDF redaction"),
        "deadline": loc("Przeciwnik i sąd czekają na projekt do 16:00", "Opponent and court wait for the draft until 16:00"),
        "context": loc(
            "Ugoda patentowa. Klient — spółka z branży, która nie chce kwot licencji na wokandzie ani w prasie. Iglica „zasłonił” liczby czarnymi prostokątami w podglądzie. Plik waży tyle samo. Warstwa tekstu nadal leży pod prostokątem. Za żaluzją — Śródmieście, 16:00 to jutro w pismach.",
            "A patent settlement. The client — a company that does not want licence figures on the docket or in the press. Iglica “covered” the numbers with black rectangles in preview. The file weighs the same. The text layer still sits under the box. Beyond the blinds — downtown; 16:00 is tomorrow in the pleadings.",
        ),
        "beats": [
            beat("OfficeNight",
                 "Projekt ugody patentowej ma wyjść do sądu i przeciwnika o 16:00. Kwoty licencji mają pozostać poufne.",
                 "The patent-settlement draft must reach the court and opponent by 16:00. The licence figures must remain confidential."),
            beat("AplikantIglica",
                 "Zakryłem każdą kwotę czarnym prostokątem w podglądzie PDF. Na ekranie nic nie widać.",
                 "I covered every figure with a black rectangle in the PDF preview. Nothing is visible on screen.",
                 "balloon"),
            beat("Mission04",
                 "Właściwości pliku: „flattened: false”. Po zaznaczeniu tekstu spod prostokąta wraca 4 200 000 EUR.",
                 "File properties: “flattened: false”. Selecting the text beneath the box returns EUR 4,200,000."),
            beat("MecenasPOV",
                 "Odbiorcy czekają. Na biurku są ten PDF i oryginał; trzeba zdecydować, który plik może wyjść z kancelarii.",
                 "The recipients are waiting. The PDF and the original lie on the desk; you must decide which file may leave the firm."),
        ],
        "exhibitLabel": loc("PDF — właściwości warstw", "PDF — layer properties"),
        "exhibitText": loc(
            "redaction_boxes: 12\nflattened: false\nextractable_text: \"licencja 4 200 000 EUR, royalty 8%, know-how…\"\nmetadane: autor = F. Iglica, kancelaria, Świętokrzyska",
            "redaction_boxes: 12\nflattened: false\nextractable_text: \"licence EUR 4,200,000, royalty 8%, know-how…\"\nmetadata: author = F. Iglica, firm, Świętokrzyska",
        ),
        "innerVoice": loc(
            "Podgląd wygląda czysto, ale plik ma więcej niż warstwę obrazu. Jak sprawdzisz rezultat, zanim trafi do odbiorców?",
            "The preview looks clean, but the file contains more than the visible image. How will you test the result before it reaches the recipients?",
        ),
        "redFlags": [
            loc("Prostokąty tylko przykrywają treść — tekst i obiekty nadal są w pliku.", "The rectangles only cover content — text and objects remain in the file."),
            loc("Metadane autora i ścieżki kancelarii w pliku.", "Author and firm-path metadata still in the file."),
            loc("Kwoty licencji są objęte tajemnicą zawodową i mogą spełniać przesłanki tajemnicy przedsiębiorstwa.", "Licence figures are covered by professional secrecy and may meet the statutory trade-secret conditions."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(t=-40, s=-20, r=-20),
                ("STEMPEL", "STAMP"),
                ("Wyślij PDF", "Send the PDF"),
                ratio(
                    ("Art. 6 Prawa o adwokaturze i art. 3 ust. 3 ustawy o radcach prawnych chronią tajemnicę zawodową. Jeśli PDF zawiera dane osobowe, znaczenie mają zasada integralności i poufności oraz art. 32 RODO. Zakres naruszenia zależy od odbiorcy i upoważnienia.",
                     "Art. 6 of the Bar Act and art. 3(3) of the Legal Advisers Act protect professional secrecy. If the PDF contains personal data, GDPR integrity, confidentiality and art. 32 safeguards may apply. The scope of a breach depends on the recipient and authority to disclose."),
                    ("Odbiorca może skopiować tekst spod prostokąta. Ujawnienie może naruszyć tajemnicę zawodową, umowę lub tajemnicę przedsiębiorstwa; skutki procesowe i RODO zależą od treści oraz kręgu odbiorców.",
                     "A recipient may copy text from beneath the rectangle. Disclosure may breach professional secrecy, contract or trade-secret protection; procedural and GDPR consequences depend on the content and recipients."),
                    ("Redakcja oznacza nieodwracalne usunięcie treści narzędziem do redakcji, usunięcie komentarzy, załączników i zbędnych metadanych oraz kontrolę kopii wynikowej przez wyszukiwanie, kopiowanie i ekstrakcję tekstu.",
                     "Redaction means irreversible removal with a redaction tool, removal of comments, attachments and unnecessary metadata, and testing the output copy by search, copy and text extraction."),
                    ("Publiczne wpadki z „black boxes” w PDF-ach sądowych i due diligence — ten sam mechanizm co tu.",
                     "Public failures of courtroom and due-diligence “black boxes” — the same mechanism as here."),
                ),
            ),
            choice(
                "reject", "reject", "sound", delta(k=-8, r=+5),
                ("ODRZUT", "REJECT"),
                ("Nie wysyłaj tego pliku", "Do not send this file"),
                ratio(
                    ("Tajemnica (art. 6 / art. 3 ust. 3) obejmuje know-how i kwoty. Odrzut chroni, ale 16:00 stoi.",
                     "Secrecy (art. 6 / art. 3(3)) covers know-how and figures. Rejection protects, but 16:00 still stands."),
                    ("Iglica musi zrobić prawdziwą redakcję. Partner Chropot dostaje SMS: „projekt godzinę później, za to szczelny”.",
                     "Iglica must do a real redaction. Partner Chropot gets a text: “draft an hour later, but sealed”."),
                    ("Odrzut + checklista: narzędzie trwałej redakcji, komentarze i załączniki, metadane, druga para oczu oraz test tekstu wynikowego.",
                     "Reject + checklist: permanent-redaction tool, comments and attachments, metadata, second pair of eyes and output-text testing."),
                    ("Najlepszy pomysł z tej teczki: prostokąt bez spłaszczenia to teatr, nie redakcja.",
                     "The best idea in this file: a box without flattening is theatre, not redaction."),
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(t=+10, r=+10),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("Trwała redakcja + test", "Permanent redaction + test"),
                ratio(
                    ("Obowiązek ochrony tajemnicy istnieje niezależnie od RODO; gdy dokument zawiera dane osobowe, art. 32 RODO wymaga środków odpowiednich do ryzyka. Skuteczność redakcji trzeba sprawdzić przed wysłaniem.",
                     "The duty to protect professional secrecy exists independently of GDPR; where the document contains personal data, GDPR art. 32 requires measures appropriate to risk. Redaction effectiveness must be tested before sending."),
                    ("Ekstrakcja tekstu zwraca pełne kwoty. Iglica używa funkcji trwałej redakcji usuwającej właściwe obiekty, czyści komentarze, załączniki i zbędne metadane, a druga osoba testuje kopię wynikową.",
                     "Text extraction returns the full figures. Iglica uses a permanent-redaction function that removes the relevant objects, clears comments, attachments and unnecessary metadata, and a second person tests the output copy."),
                    ("Zasada: jeśli wyszukiwanie, kopiowanie albo ekstrakcja odzyskuje treść — pliku nie wysyłasz. Samo spłaszczenie ani eksport do obrazu nie daje gwarancji redakcji.",
                     "Rule: if search, copy or extraction recovers the content, do not send the file. Flattening or export to an image alone does not guarantee redaction."),
                    ("To nie jest „AI Act”. To jest warstwa PDF i tajemnica.",
                     "This is not the AI Act. It is a PDF layer and secrecy."),
                ),
            ),
        ],
    },
    {
        "id": "05-pendrive",
        "order": 5,
        "demo": False,
        "exhibit": "usb",
        "hero": "Mission05",
        "tone": "shadow",
        "title": loc("Pendrive w koszulce", "A stick in a sleeve"),
        "subtitle": loc("Akta · nośnik od kuriera", "Files · courier media"),
        "deadline": loc("Irena: „kurier zostawił, pan mecenas ma czytać wieczorem”", "Irena: “the courier left it, counsel is to read tonight”"),
        "context": loc(
            "Irena z sekretariatu stoi w drzwiach gabinetu na 5. piętrze. Koszulka, pendrive, napis COURIER. „Od pełnomocnika przeciwnika — akta uzupełniające. Podobno z uprzejmości prokuratury.” Nie ma pisma przewodniego w uzgodnionym kanale. Port USB w laptopie kancelarii jest odblokowany.",
            "Irena from the secretariat stands in the 5th-floor doorway. A sleeve, a stick, the word COURIER. “From opposing counsel — supplemental files. Apparently a courtesy from the prosecutor’s office.” There is no cover letter in the agreed channel. The USB port on the firm laptop is unlocked.",
        ),
        "beats": [
            beat("SekretariatIrena",
                 "Kurier zostawił tę koszulkę. Podobno od pełnomocnika przeciwnika, z uprzejmości prokuratury.",
                 "A courier left this sleeve. Supposedly from opposing counsel, as a courtesy from the prosecutor’s office.",
                 "balloon"),
            beat("Mission05",
                 "W środku: niezaszyfrowany SanDisk 32 GB z napisem „uzupełnienie akt”. Brak podpisanego pisma przewodniego.",
                 "Inside: an unencrypted 32 GB SanDisk marked “supplemental file”. There is no signed cover letter."),
            beat("MecenasPOV",
                 "Nadawcy nie potwierdzono w uzgodnionym kanale. Obok leży laptop kancelarii z odblokowanym portem USB.",
                 "The sender has not been confirmed through the agreed channel. Beside it sits the firm laptop with an unlocked USB port."),
            beat("OfficeNight",
                 "Irena czeka w drzwiach: „Mam go włożyć, żeby pan mecenas mógł czytać wieczorem?”",
                 "Irena waits in the doorway: “Should I plug it in so counsel can read it tonight?”",
                 "balloon"),
        ],
        "exhibitLabel": loc("NOŚNIK — etykieta", "MEDIA — label"),
        "exhibitText": loc(
            "SanDisk 32 GB, bez szyfrowania.\nMarker: „UZUPEŁNIENIE AKT — W. v. K.”\nAutor plików wg metadanych: nieznany.\nIrena: „zawsze tak przynoszą”.",
            "SanDisk 32 GB, unencrypted.\nMarker: “SUPPLEMENTAL FILE — W. v. K.”\nFile metadata author: unknown.\nIrena: “they always bring them this way”.",
        ),
        "innerVoice": loc(
            "Nie wiesz jeszcze, kto przygotował nośnik ani co uruchomi komputer po podłączeniu. Jak ustalisz pochodzenie i zawartość bez narażania stacji z aktami?",
            "You do not yet know who prepared the device or what the computer will run when it is connected. How will you establish provenance and contents without exposing the workstation holding files?",
        ),
        "redFlags": [
            loc("Nieznane pochodzenie i brak pisma przewodniego w uzgodnionym kanale.", "Unknown provenance and no cover letter in the agreed channel."),
            loc("Irena nie jest IT — jest mostem.", "Irena is not IT — she is a bridge."),
            loc("Port USB otwarty na laptopie z aktami.", "An open USB port on a laptop that holds files."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(t=-45, r=-35),
                ("STEMPEL", "STAMP"),
                ("Włóż i otwórz", "Plug in and open"),
                ratio(
                    ("Obcy nośnik wymaga procedury cyberbezpieczeństwa i ochrony tajemnicy. Jeżeli zawiera dane osobowe, znaczenie mają zasady integralności i poufności oraz środki z art. 32 RODO; art. 25 nie jest ogólną podstawą skanowania USB.",
                     "Foreign media requires a cybersecurity and professional-secrecy procedure. If it contains personal data, GDPR integrity, confidentiality and art. 32 safeguards matter; art. 25 is not a general legal basis for scanning USB media."),
                    ("Podłączenie może uruchomić złośliwy kod lub narazić akta dostępne na stacji. To odrębny stan faktyczny od decyzji DKN.5131.31.2022 o zagubionym, wysłanym bez szyfrowania nośniku.",
                     "Connecting it may execute malicious code or expose files accessible from the workstation. This differs from DKN.5131.31.2022, which concerned an unencrypted device lost in transit."),
                    ("Nie podłączaj do stacji z aktami. Zarejestruj odbiór, potwierdź nadawcę znanym kanałem i przekaż nośnik IT do analizy w kontrolowanym, odseparowanym środowisku albo poproś o ponowne doręczenie zatwierdzonym kanałem.",
                     "Do not connect it to a workstation holding files. Log receipt, confirm the sender through a known channel, and give the media to IT for analysis in a controlled isolated environment, or request redelivery through an approved channel."),
                    ("DKN.5131.31.2022; II SA/Wa 1342/23.",
                     "DKN.5131.31.2022; II SA/Wa 1342/23."),
                    STORY_UODO,
                ),
            ),
            choice(
                "reject", "reject", "sound", delta(k=-5, r=+6),
                ("ODRZUT", "REJECT"),
                ("Zwróć Irenie, nie włączać", "Give it back to Irena, do not mount"),
                ratio(
                    ("Art. 32 RODO — odpowiednie środki. Odrzut nośnika bez łańcucha jest środkiem, nie niegrzecznością.",
                     "GDPR art. 32 — appropriate measures. Rejecting media without a chain is a measure, not rudeness."),
                    ("Irena wraca do kuriera z prośbą o kanał uzgodniony. Przeciwnik może marudzić. Akta nie wchodzą na laptop mecenasa.",
                     "Irena goes back to the courier for an agreed channel. Opposing counsel may grumble. The files do not enter counsel’s laptop."),
                    ("Tabliczka u Ireny: żaden USB do laptopów kancelarii. Wyjątek — po IT.",
                     "A plate at Irena’s desk: no USB into firm laptops. Exception — after IT."),
                    ("UODO nie pyta, czy „zawsze tak przynoszą”. DKN.5131.31.2022.",
                     "The DPA does not ask whether “they always bring them this way”. DKN.5131.31.2022."),
                    STORY_UODO,
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(t=+8, r=+10),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("IT / stacja-kwarantanna", "IT / quarantine box"),
                ratio(
                    ("Podstawą operacyjną jest procedura bezpieczeństwa kancelarii; art. 32 RODO ma zastosowanie, jeżeli przetwarzane są dane osobowe. Izolacja i skan ograniczają ryzyko, ale suma kontrolna sama nie wykrywa malware.",
                     "The firm’s security procedure is the operational basis; GDPR art. 32 applies where personal data is processed. Isolation and scanning reduce risk, but a checksum alone does not detect malware."),
                    ("IT nie wykrywa zagrożenia w kontrolowanym środowisku, a nadawca potwierdza przesyłkę. Pliki trafiają do zatwierdzonego zasobu; nośnik przechowujecie albo zwracacie zgodnie z protokołem i prawem własności — bez samowolnego niszczenia.",
                     "IT finds no threat in the controlled environment and the sender confirms the delivery. Files move to an approved store; retain or return the device under procedure and property rules—do not destroy it unilaterally."),
                    ("Polityka nośników: Irena nie decyduje. Mecenas nie „tylko zerknie”.",
                     "Media policy: Irena does not decide. Counsel does not “just peek”."),
                    ("DKN.5131.31.2022 — kancelaria, nie korporacja.",
                     "DKN.5131.31.2022 — a law firm, not a corporation."),
                    STORY_UODO,
                ),
            ),
        ],
    },
    {
        "id": "06-mail",
        "order": 6,
        "demo": False,
        "exhibit": "email",
        "hero": "Mission06",
        "tone": "shadow",
        "title": loc("Mail prawie od mecenasa", "Mail almost from counsel"),
        "subtitle": loc("BEC · myślnik w domenie", "BEC · a hyphen in the domain"),
        "deadline": loc("„Proszę zwrócić klientowi 240 tys. zł niewykorzystanej zaliczki — dziś do 15:00”", "“Return PLN 240k of the client’s unused retainer — today by 15:00”"),
        "context": loc(
            "Skrzynka na 5. piętrze. Księgowość kancelarii ma zwrócić klientowi — posłowi, który „nie może się pokazać w tej sprawie” — 240 tys. zł niewykorzystanej zaliczki przechowywanej na rachunku kancelarii. Nadawca: chropot@colgante-partners.com, choć właściwa domena to colgante.pl. Wiadomość podaje nowy „tymczasowy” rachunek klienta.",
            "The 5th-floor inbox. The firm’s accounts team is to return PLN 240k of an unused retainer held in the firm account to the client—an MP who “cannot be seen in this matter”. The sender is chropot@colgante-partners.com although the correct domain is colgante.pl. The message gives a new “temporary” client account.",
        ),
        "beats": [
            beat("OfficeNight",
                 "Księgowość ma zwrócić klientowi 240 tys. zł niewykorzystanej zaliczki. Wiadomość żąda przelewu do 15:00.",
                 "Accounts must return PLN 240k of the client’s unused retainer. The message demands the transfer by 15:00."),
            beat("Mission06",
                 "Nadawca: chropot@colgante-partners.com. W treści: nowy „tymczasowy” IBAN i prośba, żeby nie dzwonić.",
                 "Sender: chropot@colgante-partners.com. The message contains a new “temporary” IBAN and asks for no phone call."),
            beat("PartnerChropot",
                 "W podpisanej korespondencji Chropota widnieje colgante.pl. Nagłówek nowego maila nie potwierdza serwera nadawcy: SPF fail.",
                 "Chropot’s signed correspondence uses colgante.pl. The new message header does not authenticate the sender’s server: SPF fail."),
            beat("MecenasPOV",
                 "Kwota czeka na rachunku kancelarii. Mail wskazuje inny rachunek niż wcześniejsze dyspozycje klienta.",
                 "The money remains in the firm’s account. The e-mail points to an account different from the client’s previous instructions."),
        ],
        "exhibitLabel": loc("NAGŁÓWEK SMTP", "SMTP HEADER"),
        "exhibitText": loc(
            "From: Partner Chropot <chropot@colgante-partners.com>\nReply-To: finance@colgante-partners.com\nSPF: fail\n„Jestem u klienta. Zaliczka 240 tys. zł na IBAN w treść. Nie dzwoń — rozprawa.”",
            "From: Partner Chropot <chropot@colgante-partners.com>\nReply-To: finance@colgante-partners.com\nSPF: fail\n“I’m at the client. Retainer PLN 240k, IBAN in the body. Don’t call — I’m in a hearing.”",
        ),
        "innerVoice": loc(
            "Mail naśladuje styl partnera, ale zmienia kanał i rachunek. Co jest sygnałem ostrzegawczym, a co może wiarygodnie potwierdzić dyspozycję?",
            "The message imitates the partner’s style but changes both channel and account. What is merely a warning signal, and what can reliably confirm the instruction?",
        ),
        "redFlags": [
            loc("Domena z myślnikiem ≠ papier firmowy.", "Hyphenated domain ≠ letterhead."),
            loc("SPF fail.", "SPF fail."),
            loc("Zakaz telefonu + nowy IBAN.", "A ban on calling + a new IBAN."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(k=-50, r=-35),
                ("STEMPEL", "STAMP"),
                ("Zwróć zaliczkę na nowy rachunek", "Refund the retainer to the new account"),
                ratio(
                    ("Sposób dysponowania środkami klienta wyznaczają umowa i reguły zawodowe, w tym § 6 Regulaminu wykonywania zawodu adwokata lub art. 37 KERP. Brak weryfikacji nowej dyspozycji może — zależnie od umowy, szkody i winy — prowadzić do odpowiedzialności m.in. na podstawie art. 355 § 2 i 471 k.c.",
                     "The client agreement and professional rules govern client money, including § 6 of the advocate-practice regulations or KERP art. 37. Failure to verify new instructions may—depending on contract, loss and fault—lead to civil liability under, among other provisions, Civil Code arts. 355 § 2 and 471."),
                    ("240 tys. zł na rachunek cienia. Thomas v. Corbyn 2025 — prawie identyczny list.",
                     "PLN 240k to a shadow account. Thomas v. Corbyn 2025 — almost the same letter."),
                    ("Porównaj pełną domenę z adresem zapisanym wcześniej. Wynik SPF/DMARC jest sygnałem technicznym, nie samodzielnym dowodem. Zadzwoń na numer z akt, nie z podejrzanej wiadomości.",
                     "Compare the full domain with the address recorded earlier. SPF/DMARC results are technical signals, not standalone proof. Call the number on file, not one in the suspect message."),
                    ("Thomas v. Corbyn 2025; klasyczny BEC z lookalike domain.",
                     "Thomas v. Corbyn 2025; classic lookalike-domain BEC."),
                    STORY_THOMAS,
                ),
            ),
            choice(
                "reject", "reject", "incomplete", delta(k=-12),
                ("ODRZUT", "REJECT"),
                ("Skasuj mail", "Delete the mail"),
                ratio(
                    ("Skasowanie bez zgłoszenia zostawia kolejnego adresata w łańcuchu — Irenę, księgowość, aplikanta.",
                     "Deleting without a report leaves the next addressee in the chain — Irena, accounts, a trainee."),
                    ("Mail wróci o 14:55 z jeszcze ostrzejszym deadline’em.",
                     "The mail will return at 14:55 with a sharper deadline."),
                    ("Odrzut = zgłoś IT, oznacz phishing, callback do Chropota.",
                     "Reject = tell IT, tag phishing, callback to Chropot."),
                    ("BEC żyje z tego, że jeden człowiek „nie chciał robić afery”.",
                     "BEC lives on one person who “did not want a fuss”."),
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(k=+8, r=+12),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("Domena + telefon", "Domain + phone"),
                ratio(
                    ("Weryfikacja kanału: pełna domena i nagłówki ocenione przez IT oraz callback na numer zapisany wcześniej. SPF może zawieść także przy legalnym przekierowaniu, więc nie zastępuje callbacku.",
                     "Channel verification: the full domain and headers reviewed by IT, plus callback to a number recorded in advance. SPF can also fail after legitimate forwarding, so it does not replace callback."),
                    ("Chropot z colgante.pl: „nie pisałem”. IT blokuje lookalike. Zaliczka stoi na właściwym rachunku z umowy.",
                     "Chropot at colgante.pl: “I did not write that.” IT blocks the lookalike. The retainer stays on the contract account."),
                    ("Wyświetlaj pełną domenę. Każdy nowy lub zmieniony IBAN potwierdzaj niezależnym, wcześniej uzgodnionym kanałem.",
                     "Display the full domain. Confirm every new or changed IBAN through an independent channel agreed in advance."),
                    ("Thomas v. Corbyn 2025.",
                     "Thomas v. Corbyn 2025."),
                    STORY_THOMAS,
                ),
            ),
        ],
    },
    {
        "id": "07-copilot",
        "order": 7,
        "demo": False,
        "exhibit": "memo",
        "hero": "Mission07",
        "tone": "shadow",
        "title": loc("Nasz Copilot też kłamie", "Our Copilot lies too"),
        "subtitle": loc("Notatka wewnętrzna · halucynacja", "Internal memo · hallucination"),
        "deadline": loc("Zarząd klienta chce memo do 18:00", "The client’s board wants the memo by 18:00"),
        "context": loc(
            "Zarząd spółki z przetargowym cieniem chce opinii o odpowiedzialności członków zarządu — na komisję, nie do prasy. Iglica użył kancelaryjnego Copilota — ten z licencją, nie z chatgpt.com. Notatka cytuje „III CZP 7/24” i „wyrok TSUE w sprawie C-404/23 Board Duty”. Brzmi gładko. Chropot z pociągu: „wysyłaj, skoro nasz”.",
            "The board of a company with a tender-shaped shadow wants an opinion on directors’ duties — for a committee, not the press. Iglica used the firm Copilot — the licensed one, not chatgpt.com. The memo cites “III CZP 7/24” and “CJEU C-404/23 Board Duty”. It reads smooth. Chropot from the train: “send it, it’s ours”.",
        ),
        "beats": [
            beat("OfficeNight",
                 "Zarząd klienta czeka do 18:00 na memo o odpowiedzialności członków zarządu za użycie AI.",
                 "The client’s board expects a memo by 18:00 on directors’ responsibility for the use of AI."),
            beat("AplikantIglica",
                 "Napisał je nasz licencjonowany Copilot. Jest DPA, a tekst brzmi jak gotowa opinia.",
                 "Our licensed Copilot wrote it. There is a DPA, and the text reads like a finished opinion.",
                 "balloon"),
            beat("PartnerChropot",
                 "Wysyłaj, skoro nasz.",
                 "Send it. It’s ours.",
                 "balloon"),
            beat("Mission07",
                 "Memo przypisuje dwóm konkretnym sygnaturom daleko idące tezy o AI. Nie zawiera linków ani ECLI.",
                 "The memo attributes broad AI holdings to two specific docket numbers. It contains no links or ECLI."),
        ],
        "exhibitLabel": loc("MEMO — wersja Copilot", "MEMO — Copilot cut"),
        "exhibitText": loc(
            "„Zgodnie z III CZP 7/24 członek zarządu odpowiada gwarancyjnie za prompt AI. TSUE w C-404/23 Board Duty potwierdza obowiązek „human in the loop” w każdej spółce akcyjnej.”",
            "“Per III CZP 7/24 a director is strictly liable for an AI prompt. CJEU C-404/23 Board Duty confirms a “human in the loop” duty in every public company.”",
        ),
        "innerVoice": loc(
            "Umowa z dostawcą opisuje ochronę danych. Czy mówi również coś o prawdziwości każdej sygnatury i tezy wygenerowanej w memo?",
            "The vendor agreement describes data protection. Does it also establish the accuracy of every docket number and holding generated in the memo?",
        ),
        "redFlags": [
            loc("III CZP 7/24 istnieje, ale dotyczy rozliczeń byłych konkubentów — nie AI.", "III CZP 7/24 exists but concerns property settlements between former cohabitants—not AI."),
            loc("C-404/23 istnieje jako Luxone/Sofein v Consip, ECLI:EU:C:2024:805 — nie „Board Duty”.", "C-404/23 exists as Luxone/Sofein v Consip, ECLI:EU:C:2024:805—not “Board Duty”."),
            loc("„Nasz Copilot” ≠ weryfikacja.", "“Our Copilot” ≠ verification."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(s=-45, r=-25, k=-15),
                ("STEMPEL", "STAMP"),
                ("Wyślij memo do zarządu", "Send the memo to the board"),
                ratio(
                    ("§ 23e KEA (tekst jednolity ogłoszony 23.06.2026) — technologia ma rolę wspomagającą, a adwokat zachowuje własną ocenę i odpowiedzialność. W skonsolidowanym AI Act art. 4 wymaga od dostawców i podmiotów stosujących wspierania rozwoju kompetencji AI personelu; nie certyfikuje konkretnego wyniku.",
                     "KEA § 23e (consolidated text published 23 Jun 2026) makes technology auxiliary while the advocate retains judgment and responsibility. In the consolidated AI Act, art. 4 requires providers and deployers to support staff AI-literacy development; it does not certify a particular output."),
                    ("Zarząd cytuje nieistniejące orzeczenie w uchwale. Albo sąd. Cork v Smith / Pinsent Masons, maj 2026 — halucynacja in-house.",
                     "The board quotes a phantom authority in a resolution. Or a court does. Cork v Smith / Pinsent Masons, May 2026 — an in-house hallucination."),
                    ("Każdy cytat z Copilota otwierasz w reporterze. Licencja nie jest stemplem.",
                     "Every Copilot cite you open in the reporter. The licence is not a stamp."),
                    ("Pinsent Masons / Cork, May 2026.",
                     "Pinsent Masons / Cork, May 2026."),
                    STORY_CORK,
                ),
            ),
            choice(
                "reject", "reject", "sound", delta(k=-8, r=+5),
                ("ODRZUT", "REJECT"),
                ("Nie wysyłaj tej wersji", "Do not send this cut"),
                ratio(
                    ("§ 23e — nie podpisujesz outputu, którego nie sprawdziłeś. Odrzut memo chroni sąd i klienta, psuje godzinę.",
                     "§ 23e — you do not sign output you have not checked. Rejecting the memo protects court and client, and burns an hour."),
                    ("Iglica wraca do kodeksu spółek i prawdziwych orzeczeń. Zarząd dostaje memo o 19:00, za to z ECLI.",
                     "Iglica goes back to the commercial companies code and real cases. The board gets the memo at 19:00, with an ECLI."),
                    ("Odrzut + lista sygnatur do sprawdzenia, nie „napisz od nowa”.",
                     "Reject + a list of cites to check, not “write it again”."),
                    ("In-house nie znaczy „nie halucynuje”.",
                     "In-house does not mean “does not hallucinate”."),
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(s=+8, r=+12),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("sn.pl / EUR-Lex", "sn.pl / EUR-Lex"),
                ratio(
                    ("AI Act art. 4 dotyczy wspierania rozwoju kompetencji personelu przez dostawcę lub podmiot stosujący. Konkretny obowiązek własnej oceny rezultatu przez adwokata wynika z § 23e KEA. Drugi kanał: oficjalny portal SN i EUR-Lex.",
                     "AI Act art. 4 concerns providers and deployers supporting staff AI-literacy development. The advocate’s specific duty to assess output follows from KEA § 23e. Use the official Supreme Court portal and EUR-Lex as a second channel."),
                    ("Obie sygnatury istnieją, lecz dotyczą innych spraw. III CZP 7/24 dotyczy rozliczeń byłych konkubentów; C-404/23 rozstrzygnięto z C-403/23 jako Luxone/Sofein v Consip, ECLI:EU:C:2024:805, w sprawie zamówień publicznych.",
                     "Both docket numbers exist but concern different disputes. III CZP 7/24 concerns former cohabitants’ property settlement; C-404/23 was decided with C-403/23 as Luxone/Sofein v Consip, ECLI:EU:C:2024:805, on public procurement."),
                    ("Zasada kancelarii: zielona lampka Copilota nie zastępuje ECLI.",
                     "Firm rule: Copilot’s green light does not replace an ECLI."),
                    ("Pinsent 2026 — ostrzeżenie dla tych, którzy „już mają licencję”.",
                     "Pinsent 2026 — a warning for those who “already have a licence”."),
                    STORY_CORK,
                ),
            ),
        ],
    },
    {
        "id": "08-emocje",
        "order": 8,
        "demo": False,
        "exhibit": "hr",
        "hero": "Mission08",
        "tone": "probono",
        "title": loc("Kamera na minie", "A camera on her face"),
        "subtitle": loc("Pro bono · emotion AI w miejscu pracy", "Pro bono · workplace emotion AI"),
        "deadline": loc("Irena: „pro bono, ale dostawca już stoi w newsroomie”", "Irena: “pro bono, but the vendor is already in the newsroom”"),
        "context": loc(
            "Sala 14B, to samo 5. piętro. Irena kładzie teczkę z czerwoną wstążką: nie faktura. Pro bono. Klientka — dziennikarka śledcza. Newsroom chce kamerę na „rozmowie integralności” po publikacji. Dostawca sprzedaje scoring stresu jako „zgodność z AI Act art. 4”. To nie jest analityka sędziego. To miejsce pracy.",
            "Room 14B, same 5th floor. Irena lays down a file with a red ribbon: not an invoice. Pro bono. The client — an investigative journalist. The newsroom wants a camera on an “integrity interview” after a story. The vendor sells a stress score as “AI Act art. 4 aligned”. This is not judge analytics. This is a workplace.",
        ),
        "beats": [
            beat("OfficeNight",
                 "Po północy. Teczka z czerwoną wstążką: sprawa pro bono dziennikarki śledczej.",
                 "After midnight. A red-ribbon file: an investigative journalist’s pro bono matter."),
            beat("SekretariatIrena",
                 "Dostawca już stoi w newsroomie. Kamera ma obserwować jej twarz podczas rozmowy integralności.",
                 "The vendor is already in the newsroom. A camera is to watch her face during an integrity interview.",
                 "balloon"),
            beat("Mission08",
                 "Oferta: rozpoznawanie emocji z obrazu twarzy, scoring stresu i zapis wyniku do akt osobowych.",
                 "The offer: emotion recognition from facial images, a stress score and storage of the result in the personnel file."),
            beat("MecenasPOV",
                 "Na pierwszej stronie ulotki: „zgodność z AI Act art. 4”. Nie opisano celu medycznego ani bezpieczeństwa.",
                 "The brochure’s first page says “AI Act art. 4 aligned”. No medical or safety purpose is described."),
        ],
        "exhibitLabel": loc("OFERTA DOSTAWCY — fragment", "VENDOR PITCH — excerpt"),
        "exhibitText": loc(
            "„Moduł emotion recognition w czasie rzeczywistym na rozmowie integralności z pracownikiem newsroomu. Zgodność z AI Act art. 4 (literacy). Scoring do teczki osobowej. Cena: 900 zł / etat / miesiąc.”",
            "“Real-time emotion recognition on an integrity interview with a newsroom employee. AI Act art. 4 (literacy) aligned. Score into the personnel file. Price: PLN 900 / head / month.”",
        ),
        "innerVoice": loc(
            "Ulotka wskazuje art. 4, lecz system ma działać wobec pracownicy w newsroomie. Które przepisy trzeba przeczytać razem, zanim ocenisz ofertę?",
            "The brochure cites article 4, but the system will operate on an employee in a newsroom. Which provisions must be read together before you assess the offer?",
        ),
        "redFlags": [
            loc("Rozpoznawanie emocji w miejscu pracy — art. 5 ust. 1 lit. f AI Act.", "Workplace emotion recognition — AI Act art. 5(1)(f)."),
            loc("Art. 4 (literacy) nie uchyla zakazu art. 5.", "Art. 4 (literacy) does not lift the art. 5 ban."),
            loc("Nie mieszaj tego z profilowaniem sędziów.", "Do not mix this with judge-profiling."),
        ],
        "choices": [
            choice(
                "stamp", "stamp", "unsound", delta(r=-50, k=-10, t=-15),
                ("STEMPEL", "STAMP"),
                ("Zatwierdź kamerę w newsroomie", "Clear the camera for the newsroom"),
                ratio(
                    ("AI Act art. 5 ust. 1 lit. f zakazuje wprowadzania do obrotu, oddawania do użytku w tym celu i stosowania systemów AI, które wnioskują o emocjach osoby w miejscu pracy lub edukacji na podstawie danych biometrycznych, z wyjątkiem zastosowań medycznych lub bezpieczeństwa. Zakaz stosuje się od 2.02.2025.",
                     "AI Act art. 5(1)(f) prohibits placing on the market, putting into service for that purpose, or using AI systems that infer a person’s emotions in workplace or education from biometric data, except for medical or safety reasons. The prohibition applies from 2 Feb 2025."),
                    ("Wdrożenie może uruchomić nadzór i odpowiedzialność z AI Act, RODO oraz prawa pracy. Art. 99 określa maksima sankcji; nie oznacza automatycznej kary 7% za każdy przypadek.",
                     "Deployment may trigger supervision and liability under the AI Act, GDPR and employment law. Article 99 sets maximum penalties; it does not impose an automatic 7% fine in every case."),
                    ("Nie wdrażaj systemu wnioskującego emocje z danych biometrycznych w miejscu pracy, chyba że udokumentowana analiza wykaże zastosowanie wyjątku medycznego lub bezpieczeństwa. Art. 4 nie uchyla art. 5.",
                     "Do not deploy a workplace system that infers emotions from biometric data unless a documented analysis establishes the medical or safety exception. Article 4 does not displace article 5."),
                    ("Za naruszenie art. 5 art. 99 ust. 3 przewiduje maksimum 35 mln EUR albo 7% światowego rocznego obrotu przedsiębiorstwa; co do zasady dla przedsiębiorstw stosuje się kwotę wyższą, a dla MŚP niższą. To maksimum, nie automatyczna kara.",
                     "For a breach of art. 5, art. 99(3) sets a maximum of EUR 35m or 7% of an undertaking’s worldwide annual turnover; generally the higher amount applies to undertakings and the lower to SMEs. This is a ceiling, not an automatic fine."),
                ),
            ),
            choice(
                "reject", "reject", "sound", delta(r=+10),
                ("ODRZUT", "REJECT"),
                ("Zakaz — oddaj teczkę klientce", "Ban — give the file back to the client"),
                ratio(
                    ("Art. 5 ust. 1 lit. f AI Act — nie wdrażasz. Odrzut jest zgodnością, nie konserwatyzmem.",
                     "AI Act art. 5(1)(f) — you do not deploy. Rejection is compliance, not conservatism."),
                    ("Irena odsyła dostawcę. Klientka dostaje opinię: system jest zakazany w miejscu pracy. Newsroom zostaje rozmową, nie scoringiem miny.",
                     "Irena sends the vendor away. The client gets an opinion: the system is banned at work. The newsroom stays a conversation, not a face-score."),
                    ("Opinia wskazuje definicję systemu rozpoznawania emocji, zakres zakazu i wyjątki. Inne narzędzia HR u pracodawcy wymagają osobnej oceny.",
                     "The opinion states the definition of emotion recognition, the scope of the ban and its exceptions. Other employer HR tools require a separate assessment."),
                    ("Maksimum z art. 99 opisujesz wraz z zasadami jego obliczania i bez sugerowania, że będzie zastosowane automatycznie.",
                     "Describe the article 99 ceiling with its calculation rules and without suggesting that it applies automatically."),
                ),
            ),
            choice(
                "verify", "verify", "sound", delta(r=+12),
                ("DRUGI KANAŁ", "SECOND CHANNEL"),
                ("Tekst art. 5, nie slajd", "The text of art. 5, not the slide"),
                ratio(
                    ("AI Act art. 5 ust. 1 lit. f czytasz łącznie z art. 3 pkt 39 i motywem 18. Art. 50 ust. 2 dotyczy maszynowego oznaczania określonych syntetycznych outputów, ust. 3 informowania osób poddanych dozwolonemu emotion recognition, a ust. 4 deepfake’ów i określonych tekstów interesu publicznego.",
                     "Read AI Act art. 5(1)(f) with art. 3(39) and recital 18. Article 50(2) concerns machine-readable marking of certain synthetic outputs, paragraph 3 notice to persons exposed to lawful emotion recognition, and paragraph 4 deepfakes and certain public-interest text."),
                    ("Zakaz unijny stosuje się od 2 lutego 2025. Polska ustawa o systemach AI obowiązuje od 11 sierpnia 2026, lecz jej rozdziały o kontroli, postępowaniach i karach mają wejść w życie 28 października 2026; nie odracza to bezpośredniego zakazu z art. 5.",
                     "The EU prohibition applies from 2 February 2025. Poland’s AI systems act has applied since 11 August 2026, while its enforcement, proceedings and penalties chapters are due to apply from 28 October 2026; that does not postpone the directly applicable article 5 prohibition."),
                    ("Drugi kanał przy AI Act: EUR-Lex, nie ulotka dostawcy. Osobno oceń RODO i prawo pracy; art. 9 RODO dotyczy danych biometrycznych tylko przy przetwarzaniu w celu jednoznacznej identyfikacji, a art. 22 według przesłanek decyzji wyłącznie zautomatyzowanej.",
                     "The second channel for the AI Act is EUR-Lex, not a vendor flyer. Assess GDPR and employment law separately; GDPR art. 9 applies to biometric data only when processed to uniquely identify a person, and art. 22 only under its solely automated decision conditions."),
                    ("Art. 99 ust. 3 dotyczy naruszeń zakazów z art. 5; wysokość konkretnej kary wymaga zastosowania wszystkich reguł z art. 99.",
                     "Article 99(3) concerns breaches of article 5 prohibitions; any actual fine requires application of all article 99 rules."),
                ),
            ),
        ],
    },
]

AWARENESS = {
    "01-sygnatura": awareness(
        (
            "Narzędzie językowe potrafi zmyślić sygnaturę albo — jak w tej teczce — przypisać zmyśloną tezę prawdziwej sygnaturze. To drugi wariant jest trudniejszy do wykrycia. Pełnomocnik odpowiada za rzetelność pisma niezależnie od narzędzia. Mata i Park są przykładami amerykańskimi, nie polską podstawą sankcji.",
            "A language tool may invent a docket number or—as in this file—attach an invented holding to a real docket. The latter is harder to detect. Counsel remains responsible for a filing regardless of the tool. Mata and Park are US illustrations, not Polish grounds for sanctions.",
        ),
        (
            "Żadnej sygnatury ze stemplem, której nie otworzyłeś w źródle: Portal Orzeczeń SN / LEX / Legalis / EUR-Lex. Nie wklejaj cytatu z czatu do uzasadnienia. Przy apelacji i kasacji — cztery oczy na wykaz orzecznictwa. Presja partnera z pociągu nie zastępuje reportera.",
            "No cite under a stamp that you have not opened in a source: the Supreme Court portal / LEX / Legalis / EUR-Lex. Do not paste a chat quote into the reasons. On appeals — four eyes on the table of authorities. Pressure from a partner on a train is not a reporter.",
        ),
        (
            "Na wokandzie kancelarii: „pełny tekst → sąd i data → teza w kontekście → dopiero podpis”. § 23e KEA wymaga własnej oceny rezultatu narzędzia. Jeżeli błąd trafił do sądu, sposób korekty dobiera się do etapu i procedury; nie wolno go zatajać ani utrwalać.",
            "On the firm docket: “full text → court and date → holding in context → only then sign”. KEA § 23e requires counsel’s own assessment of tool output. If an error reached court, correction depends on the procedural stage; it must not be concealed or perpetuated.",
        ),
        [
            ("Fraza, która brzmi jak model („ograniczenie w chmurze”), a nie jak SN.", "A phrase that sounds like a model (“limitation in the cloud”), not like the Supreme Court."),
            ("Istniejąca sygnatura, ale brak przypisywanej jej tezy w pełnym tekście.", "An existing docket number, but no attributed holding in the full text."),
            ("Symbol sprawy jest prawie poprawny: `III CSK 88/21` zamiast rzeczywistego `III CSKP 88/21`.", "The case code is almost right: `III CSK 88/21` instead of the real `III CSKP 88/21`."),
            ("Deadline dziś 23:59 + telefon z wagonu = warunek, w którym ludzie przestają sprawdzać.", "Deadline tonight 23:59 + a call from a carriage = the condition in which people stop checking."),
        ],
    ),
    "02-szept": awareness(
        (
            "Wklejenie SPA lub notatki klienta do usługi konsumenckiej ujawnia treść zewnętrznemu dostawcy na jego warunkach. Trzeba oddzielnie ocenić tajemnicę zawodową, rolę dostawcy w RODO, podstawę i cel przetwarzania, retencję, dostęp oraz transfery. Art. 6 Prawa o adwokaturze i art. 3 ust. 3 ustawy o radcach prawnych chronią tajemnicę; ewentualna odpowiedzialność karna z art. 266 § 1 k.k. zależy od spełnienia znamion.",
            "Pasting an SPA or client memo into a consumer service discloses it to an external provider under consumer terms. Assess professional secrecy, the provider’s GDPR role, legal basis and purpose, retention, access and transfers separately. Polish statutory professional secrecy applies; any criminal liability under Criminal Code art. 266 § 1 depends on all elements being met.",
        ),
        (
            "Domyślnie: nie wklejaj akt do narzędzi konsumenckich. Narzędzie kancelaryjne wymaga udokumentowanej oceny umowy, roli RODO, bezpieczeństwa, retencji, transferów, dostępu i konfiguracji. DPA oraz wyłączenie treningu są ważne, lecz nie wystarczają samodzielnie. Incydent zgłasza się zgodnie z procedurą; usunięcie historii go nie cofa.",
            "Default: do not paste files into consumer tools. A firm tool requires documented review of contract, GDPR role, security, retention, transfers, access and configuration. A DPA and training opt-out matter but are not sufficient alone. Report an incident under procedure; deleting history does not undo it.",
        ),
        (
            "Nie utożsamiaj wszystkich informacji: nazwiska są danymi osobowymi, a warunki SPA mogą stanowić tajemnicę zawodową i — po spełnieniu przesłanek ustawowych — tajemnicę przedsiębiorstwa. Zgoda klienta nie zastępuje analizy obowiązków ustawowych. Audyt obejmuje także prywatne konta AI używane do pracy.",
            "Do not collapse all categories: names are personal data, while SPA terms may be covered by professional secrecy and—if statutory conditions are met—trade-secret protection. Client consent does not replace analysis of statutory duties. Audit private AI accounts used for work as well.",
        ),
        [
            ("Konto konsumenckie zamiast narzędzia zatwierdzonego przez kancelarię.", "A consumer account instead of a firm-approved tool."),
            ("Prompt z nazwiskami stron, kwotami i załącznikiem PDF.", "A prompt with party names, figures and a PDF attached."),
            ("„Tylko streszczę SPA, nic nie wyślę dalej” — model już dostał treść.", "“I’ll just summarise the SPA” — the model already has the text."),
            ("Aplikant pod presją deadline’u due diligence o 2 w nocy.", "A trainee under a 2 a.m. due-diligence deadline."),
        ],
    ),
    "03-glos": awareness(
        (
            "Vishing i BEC na środki powierzone: głos „klienta” z lotniska, domena z cyfrą (mer1dian), zakaz oddzwonienia na numer z akt, nowy IBAN „na 12 minut”. To nie jest dziwny klient — to klasyczny atak na rachunek kancelarii i na pieniądze, których nie wolno ruszyć bez weryfikacji kanałem z teczki.",
            "Vishing and BEC against client money: a “client” voice from an airport, a digit in the domain (mer1dian), a ban on calling the number on file, a new IBAN “in 12 minutes”. This is not an eccentric client — it is a textbook attack on the firm account and on funds you must not move without the channel in the file.",
        ),
        (
            "Callback wyłącznie na numer ustalony wcześniej i zapisany w aktach (nie z bieżącego maila, SMS ani załącznika). Dwie osoby zatwierdzają zmianę rachunku powyżej ustalonego progu. Nowy IBAN potwierdza się niezależnie zgodnie z procedurą. Jeśli „nie wolno dzwonić” — to flaga, nie dyskrecja.",
            "Callback only to a number established in advance and recorded in the file (not from the current email, SMS or attachment). Two people approve account changes above a defined threshold. A new IBAN is independently confirmed under procedure. “Do not call” is a warning sign, not discretion.",
        ),
        (
            "Środki powierzone: procedura na biurku Ireny i w IT. Ubezpieczyciel OC zapyta o nią po szkodzie. Deepfake głosu jest tani — „brzmi jak prezes” nie jest weryfikacją. Osobno: nie tłumacz pośpiechu „lotniskiem” — to scenariusz z playbooka BEC.",
            "Client money: a procedure on Irena’s desk and in IT. PI insurers will ask for it after a loss. Voice clones are cheap — “sounds like the CEO” is not verification. Separately: do not excuse haste with “the airport” — that is a BEC playbook.",
        ),
        [
            ("Domena z jedynką / O zamiast o / nowy TLD zamiast znanego.", "A digit in the domain / O for o / a new TLD instead of the known one."),
            ("Zakaz kontaktu na numer z pełnomocnictwa lub z KYC.", "A ban on using the number from the power of attorney or KYC."),
            ("Zmiana rachunku „tylko na ten przelew”, presja minut.", "An account change “just for this wire”, pressure in minutes."),
            ("Głos spięty, szum lotniska, prośba o milczenie wobec reszty zespołu.", "A tight voice, airport noise, a request to keep the rest of the team out."),
        ],
    ),
    "04-prostokaty": awareness(
        (
            "Czerwone prostokąty na PDF-ie nie są anonimizacją. Warstwa tekstu, obiekty i metadane zostają — pdftotext, kopiuj-wklej albo „zaznacz wszystko” wyciąga kwoty licencji, nazwiska i tajemnicę przedsiębiorstwa. Wysłanie takiego pliku do sądu, drugiej strony albo do klienta „do wiadomości” to wyciek, nie redakcja.",
            "Red boxes on a PDF are not redaction. The text layer, objects and metadata remain — pdftotext, copy-paste or select-all lifts licence figures, names and trade secrets. Sending that file to a court, the other side or a client “for information” is a leak, not redaction.",
        ),
        (
            "Prawdziwa redakcja: trwałe usunięcie właściwych obiektów, komentarzy i załączników, ograniczenie metadanych oraz test kopii wynikowej przez wyszukiwanie, kopiowanie i ekstrakcję tekstu. Samo spłaszczenie lub eksport do obrazu nie jest gwarancją. Osobny plik zredagowany i osobny oryginał do akt.",
            "Real redaction: permanent removal of the relevant objects, comments and attachments, minimisation of metadata, and testing the output by search, copy and text extraction. Flattening or export to an image alone is no guarantee. Keep a separate redacted copy and an original in the file.",
        ),
        (
            "Kwoty z umów licencyjnych są objęte tajemnicą zawodową i mogą stanowić tajemnicę przedsiębiorstwa po spełnieniu przesłanek ustawowych. Po wysyłce oceń zakres ujawnienia, tajemnicę, umowę i — gdy są dane osobowe — czy doszło do naruszenia ochrony danych.",
            "Licence figures are covered by professional secrecy and may qualify as trade secrets if statutory conditions are met. After sending, assess the disclosure, secrecy, contract and—where personal data is involved—whether a personal-data breach occurred.",
        ),
        [
            ("Rozmiar pliku prawie jak oryginał — treść nadal w środku.", "File size almost unchanged — the text is still inside."),
            ("Da się zaznaczyć „zakryty” tekst albo znaleźć go wyszukiwarką.", "You can select the “covered” text or find it with search."),
            ("Właściwości PDF: autor, ścieżka kancelarii, komentarze, wersje.", "PDF properties: author, firm path, comments, versions."),
            ("Wysyłka do sądu / pełnomocnika przeciwnika „na szybko, przed rozprawą”.", "A send to the court / opposing counsel “quickly, before the hearing”."),
        ],
    ),
    "05-pendrive": awareness(
        (
            "Pendrive od kuriera, „od klienta” albo „z sądu” ma niepotwierdzone pochodzenie i może zawierać złośliwy kod. Osobno decyzja UODO DKN.5131.31.2022 (23 580 zł) pokazuje skutki utraty wysłanego, niezaszyfrowanego nośnika. WSA oddalił skargę w II SA/Wa 1342/23, ale CBOSA oznacza wyrok jako nieprawomocny. To inny stan faktyczny niż malware.",
            "A USB stick from a courier, “the client” or “the court” has unverified provenance and may contain malicious code. Separately, Polish DPA decision DKN.5131.31.2022 (PLN 23,580) illustrates loss of an unencrypted device in transit. The administrative court dismissed the challenge in II SA/Wa 1342/23, but CBOSA marks that judgment as non-final. This differs from a malware incident.",
        ),
        (
            "Żadnego obcego USB na stacjach z aktami. Stacja kwarantanny (osobny komputer bez sieci akt), skan, albo — lepiej — szyfrowany kanał uzgodniony z klientem. Porty USB można wyłączyć polityką. Sekretariat nie jest mostem „bo kurier czeka”.",
            "No foreign USB on stations that hold files. A quarantine machine (a separate computer off the file network), a scan, or — better — an encrypted channel agreed with the client. USB ports can be locked by policy. The secretariat is not a bridge “because the courier is waiting”.",
        ),
        (
            "Procedura na recepcji: rejestr, potwierdzenie nadawcy i IT — nie „Irena włoży”. Po incydencie izoluj stację i ustal fakty. Gdy doszło do naruszenia ochrony danych, art. 33 i 34 RODO stosuje się według ich odrębnych progów ryzyka; sama obecność danych nie oznacza automatycznego zgłoszenia.",
            "Reception procedure: log receipt, confirm the sender and involve IT—not “Irena will plug it in”. After an incident isolate the workstation and establish facts. If a personal-data breach occurred, GDPR arts. 33 and 34 apply under their distinct risk thresholds; data on a device does not automatically require notification.",
        ),
        [
            ("Nieznany nośnik, brak potwierdzonego nadawcy i brak pisma w uzgodnionym kanale.", "Unknown media, no confirmed sender and no cover letter in the agreed channel."),
            ("Prośba, by „tylko otworzyć na chwilę w sekretariacie”.", "A request to “just open it for a moment at the secretariat”."),
            ("Otwarty port USB w laptopie mecenasa / aplikanta z LEX-em i skrzynką.", "An open USB port on counsel’s / the trainee’s laptop with LEX and mail."),
            ("Kurier, który „musi oddać paczkę i iść”.", "A courier who “has to drop the parcel and go”."),
        ],
    ),
    "06-mail": awareness(
        (
            "Mail „prawie od mecenasa”: domena lookalike, SPF fail, nowy IBAN do zwrotu środków klienta i zakaz telefonu. To BEC skierowany do księgowości kancelarii. Płatnikiem jest kancelaria, a przedmiotem przelewu niewykorzystana zaliczka klienta — dlatego dyspozycja musi odpowiadać umowie i procedurze środków klienta.",
            "Mail “almost from counsel”: a lookalike domain, SPF failure, a new IBAN for returning client money and a ban on calling. This is BEC aimed at the firm’s accounts team. The firm is the payer and the transfer concerns the client’s unused retainer, so the instruction must comply with the agreement and client-money procedure.",
        ),
        (
            "Zawsze pokazuj pełną domenę nadawcy, nie tylko nazwę. SPF/DKIM/DMARC ocenia IT jako zestaw sygnałów; sam SPF fail nie przesądza oszustwa. Każdą zmianę rachunku potwierdź callbackiem na numer zapisany wcześniej i zgodnie z zasadą czterech oczu. Klient przy otwarciu sprawy poznaje stałą procedurę zmian płatności.",
            "Always display the full sender domain, not merely the name. IT evaluates SPF/DKIM/DMARC as a set of signals; SPF fail alone does not prove fraud. Confirm every account change by callback to a number recorded in advance and under four-eyes control. At intake, the client receives the fixed payment-change procedure.",
        ),
        (
            "Naucz sekretariat i partnerów czytać znak po znaku (colgante-partners ≠ colgante). Paper firmowy w stopce nie uświęca domeny. Jeśli klient już przelał: bank, zawiadomienie, nie „prześlemy nowy proforma”. Ta teczka jest bliźniacza do głosu z lotniska — inny kanał, ten sam przelew.",
            "Teach secretariat and partners to read character by character (colgante-partners ≠ colgante). Letterhead in a footer does not sanctify a domain. If the client already wired: the bank, a report, not “we’ll send a new pro forma”. This file is the twin of the airport voice — another channel, the same wire.",
        ),
        [
            ("Myślnik, dodatkowe słowo, inny TLD, cyfra zamiast litery.", "A hyphen, an extra word, another TLD, a digit for a letter."),
            ("SPF / DMARC czerwone albo „wysłano z iPhone’a” przy „pilnym retainerze”.", "SPF / DMARC red, or “sent from iPhone” on an “urgent retainer”."),
            ("„Nie dzwoń, jestem na rozprawie / w samolocie.”", "“Don’t call, I’m in a hearing / on a plane.”"),
            ("Tymczasowy rachunek „tylko na ten wpis” i krótki deadline.", "A temporary account “just for this payment” and a short deadline."),
        ],
    ),
    "07-copilot": awareness(
        (
            "Licencjonowany Copilot / Harvey / wewnętrzny LLM nadal może halucynować. Zielona lampka „nasze, z DPA” nie potwierdza poprawności prawnej. Cork v Smith pokazuje błąd w pilotażu kancelaryjnym. Art. 4 AI Act wymaga wspierania rozwoju kompetencji personelu, a § 23e KEA własnej oceny rezultatu przez adwokata.",
            "A licensed Copilot / Harvey / in-house LLM may still hallucinate. A green “ours, with a DPA” light does not confirm legal accuracy. Cork v Smith illustrates failure in a firm pilot. AI Act art. 4 requires support for staff literacy development, while KEA § 23e requires the advocate’s own assessment of output.",
        ),
        (
            "Ten sam rygor co przy darmowym czacie: każda sygnatura otwarta w źródle. Copilot może szkicować strukturę, nie wykaz orzecznictwa. Zakaz „wyślij, bo to nasze narzędzie”. Szkolenie: jeden fałszywy III CZP z Copilota na zebraniu zespołu.",
            "The same rigor as with a free chat: every cite opened in a source. Copilot may sketch structure, not a table of authorities. A ban on “send it, it’s our tool”. Training: one false III CZP from Copilot in a team meeting.",
        ),
        (
            "IT i compliance kupują licencję; mecenas odpowiada za pismo. III CZP 7/24 i C-404/23 są realne, lecz trzeba przeczytać ich treść: pierwsza sprawa dotyczy rozliczeń konkubentów, druga zamówień publicznych. Prawdziwy numer nie uwierzytelnia zmyślonej tezy.",
            "IT and compliance buy the licence; counsel owns the filing. III CZP 7/24 and C-404/23 are real, but their substance must be read: the first concerns former cohabitants’ settlement and the second public procurement. A real docket number does not authenticate an invented holding.",
        ),
        [
            ("Prawdziwa sygnatura SN połączona z tezą z całkiem innej dziedziny.", "A real Supreme Court docket paired with a holding from an unrelated field."),
            ("Prawdziwy numer TSUE, ale zmyślony tytuł i teza bez zgodnego ECLI.", "A real CJEU number but an invented title and holding without a matching ECLI."),
            ("Argument „przecież mamy licencję / dane nie wychodzą”.", "The argument “we have a licence / the data does not leave”."),
            ("Partner każe „nie blokować wdrożenia Copilota” stemplem na piśmie.", "A partner orders you “not to block the Copilot rollout” with a stamp on a pleading."),
        ],
    ),
    "08-emocje": awareness(
        (
            "AI Act art. 5 ust. 1 lit. f zakazuje od 2 lutego 2025 r. systemów AI wnioskujących o emocjach osoby w miejscu pracy na podstawie danych biometrycznych, poza zastosowaniami medycznymi lub bezpieczeństwa. Oferowany scoring stresu z obrazu twarzy mieści się w zakazie, jeśli rzeczywiście dokonuje takiego wnioskowania. Art. 4 nie legalizuje wdrożenia.",
            "Since 2 February 2025, AI Act art. 5(1)(f) prohibits AI systems that infer a person’s emotions at work from biometric data, except for medical or safety reasons. The proposed facial stress score falls within the ban if it performs that inference. Article 4 does not legalise deployment.",
        ),
        (
            "Nie uruchamiaj pilota przed kwalifikacją funkcji systemu, danych biometrycznych i wyjątków. Czytaj rozporządzenie na EUR-Lex, nie ulotkę. Art. 50 reguluje odrębne obowiązki przejrzystości. Jeśli system już działa: wstrzymaj zakazaną funkcję, zabezpiecz dokumentację i oceń także RODO oraz prawo pracy.",
            "Do not start a pilot before classifying the system’s function, biometric data and exceptions. Read the regulation on EUR-Lex, not the flyer. Article 50 governs separate transparency duties. If the system is active, suspend the prohibited function, preserve documentation, and assess GDPR and employment law as well.",
        ),
        (
            "W opinii wskaż definicję z art. 3 pkt 39, zakaz z art. 5 ust. 1 lit. f i wyjątki. Osobno oceń art. 22²–22³ Kodeksu pracy, proporcjonalność, informowanie pracownika i ochronę źródeł lub sygnalisty. Art. 22 RODO ma znaczenie tylko przy decyzji wyłącznie zautomatyzowanej o skutku prawnym lub podobnie istotnym.",
            "The opinion should state the art. 3(39) definition, art. 5(1)(f) prohibition and exceptions. Separately assess Labour Code arts. 22²–22³, proportionality, employee notice and source or whistleblower protection. GDPR art. 22 matters only for solely automated decisions with legal or similarly significant effect.",
        ),
        [
            ("Obietnica scoringu stresu, szczerości, „fit kulturowy” z kamery.", "A promise to score stress, candour, “culture fit” from a camera."),
            ("Argument „art. 4 AI Act = wolno, byle przeszkolić zespół”.", "The argument “AI Act art. 4 = allowed if we train the team”."),
            ("Pilot w newsroomie / call center / naborze „tylko analitycznie”.", "A newsroom / call-centre / hiring pilot “for analytics only”."),
            ("Wynik oparty na wnioskowaniu emocji z danych biometrycznych ma trafić do akt osobowych.", "A result based on inferring emotion from biometric data is to enter the personnel file."),
        ],
    ),
}

SOURCE_IDS = {
    "01-sygnatura": ["kpc", "kea", "isap-disclaimer", "sn-search", "sn-iii-czp-12-22", "mata", "park", "cork"],
    "02-szept": ["bar", "radca", "kea", "criminal", "gdpr", "uznk", "kirp-ai", "openai-privacy", "openai-dpa", "heppner"],
    "03-glos": ["advocate-funds", "kerp-funds", "nra-cyber", "bec-gov", "thomas"],
    "04-prostokaty": ["bar", "radca", "gdpr", "uznk", "court-redaction"],
    "05-pendrive": ["gdpr", "uodo-usb", "wsa-uodo-usb", "nra-cyber", "csirt-media"],
    "06-mail": ["advocate-funds", "kerp-funds", "civil-code", "nra-cyber", "bec-gov", "thomas"],
    "07-copilot": ["kea", "aiact", "sn-iii-czp-7-24", "cjeu-c403-404", "cork"],
    "08-emocje": ["aiact", "polish-ai-act", "gdpr", "labour-code"],
}

for lesson in lessons:
    lesson["awareness"] = AWARENESS[lesson["id"]]
    lesson["sourceIds"] = SOURCE_IDS[lesson["id"]]
assert set(AWARENESS) == {x["id"] for x in lessons}
assert set(SOURCE_IDS) == {x["id"] for x in lessons}

parser = argparse.ArgumentParser()
parser.add_argument("--output", type=Path)
args = parser.parse_args()
out = args.output or (Path(__file__).resolve().parents[1] / "Resources" / "Lessons.json")
out.write_text(json.dumps(lessons, ensure_ascii=False, indent=2), encoding="utf-8")
print("lessons", len(lessons), "bytes", out.stat().st_size)
assert all(len(x["choices"]) == 3 for x in lessons)
assert sum(1 for x in lessons if x["demo"]) == 3
assert all(3 <= len(x.get("beats", [])) <= 6 for x in lessons)
assert all(len(x["beats"]) == 4 for x in lessons)
assert all(x["innerVoice"]["pl"].endswith("?") and x["innerVoice"]["en"].endswith("?") for x in lessons)
assert all("awareness" in x and len(x["awareness"]["watchFor"]) >= 4 for x in lessons)
assert all(x["sourceIds"] for x in lessons)
assert lessons[-1]["tone"] == "probono"
print("ok")
